java_test(
    name = "KafkaClientKeystoresTest",
    srcs = ["KafkaClientKeystoresTest.java"],
    resources = [
        "//kafka_certificates/src/test/resources/keystore:test_deps",
    ],
    deps = [
        "//3rdparty/jvm/com/google/guava",
        "//3rdparty/jvm/junit",
        "//kafka_certificates/src/main/java/com/tesla/data/certificates/keystore",
    ],
)

java_test(
    name = "PasswordGeneratorTest",
    srcs = ["PasswordGeneratorTest.java"],
    deps = [
        "//3rdparty/jvm/com/google/guava",
        "//3rdparty/jvm/junit",
        "//kafka_certificates/src/main/java/com/tesla/data/certificates/keystore",
    ],
)
